spring:
  datasource:
    driverClassName: ${DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/bookstore-backend?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABSE_PASSWORD:1234}
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 625004692465831
            clientSecret: ${FACEBOOK_CLIENT_SECRET}
          google:
            clientId: 462739601011-7qou3lsh8gnpl9hfn1oo2fipi49k11kg.apps.googleusercontent.com
            clientSecret: ${GOOGLE_CLIENT_SECRET}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always

  #SMTP configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: teodora.nencheva1@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#secure token configuration
secure:
  token:
    validity: 24

#cloudinary properties
cloudinary:
  api-key: 468519295473947
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: teodoran